name: Build and Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: temurin

      - name: Build with Maven
        run: mvn clean package

      - name: make new directory for .jar file
        run: mkdir staging && cp target/*.jar staging

      - name: Upload JAR
        uses: actions/upload-artifact@v4.3.4
        with:
          name: TicTacToe_Gruppe_B-jar
          path: target/*.jar